export const bingoWords = [
  "Song request after being played",
  "Glass/bottle breaks on dance floor",
  "Waiting on groom for speeches",
  "Waiting on bride for speeches",
  "5 or more glasses/bottles break on dance floor",
  "Wardobe malfunction",
  "Guest is escorted out",
  "Groomsmen is passed out drunk before dinner begins",
  "Bridesmaid is passed out drunk before dinner begins",
  "EMT/Ambulance appearance",
  "Police appearance",
  "Firefighter appearance",
  "Bridesmaid crying",
  "Awkward ex incident",
  "Grandparent asks to turn volume down",
  "Guest talking to band member while they're playing",
  "Guest asks to sit in with band",
  "Bride slaps someone",
  "Planner asks enitre band to move setup locations",
  "Dance floor is shaking from dancing",
  "Father of the bride speech is longer than 15 minutes",
  "Father of the bride speech is longer than 30 minutes",
  "Bridesmaid props during speech",
  "Requests for 'Dirty Rap'",
	"Someone proposes at the wedding",
	"Unexpected celebrity appearance",
	"Wedding cake mishap (falls over, smashes, etc.)",
	"Bestman or maid of honor forgets their speech",
  "Bouquet gets stuck/lost/destroyed during the toss",
  "Planner brings out box lunches for dinner",
  "Planner changes everything in the moment",
  "Band gets tipped",
  "Planner/Catering lets band go first through buffett",
  "Planner is drinking/drunk but tells the band not to drink",
  "Client insists the band can go to the bar",
  "Song request that clears dance floor",
  "Event finishes early",
  "Choreographed bridal party entrance",
  "Mens tie on forehead",
  "Someone getting too close to talk",
  "A guest tries to kiss a band member",
  "Someone falls during a group dance (Horah, line dance, etc...)",
  "Guest falls into band",
  "Guest repeatedly asks the same question",
  "Bride in tears (bad tears)",
  "Band member asked to do something not musical/band related (ie moving furniture)",
  "Guest is vomiting/has vomited",
  "Seeing a bear at the gig",
  "Guest rips their pants",
  "Without asking, guest(s) are trying to play band instruments",
	"Power outage"
];
